# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YH.Masonry-Demo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
	  pod 'Masonry', '~> 1.0.1'
  # Pods for YH.Masonry-Demo

end
